{
 "title": "Frontend Service Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Status Frontend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{service=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(nginx_up{service=\"frontend-service\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "__auto" },
    { "expr": "nginx_connections_writing", "legendFormat": "__auto" },
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" },
    { "expr": "nginx_connections_active", "legendFormat": "__auto" },
    {
     "expr": "rate(nginx_connections_accepted[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Numero medio di richieste",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{service=\"frontend-service\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "nginx_connections_active{service=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "nginx_http_requests_total{service=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}